const sectionColourBase = {
  artsfeatures: "#622956",
  bricksmortar: "#006469",
  business: "#005B8D",
  comment: "#850029",
  culture: "#7B0046",
  default: "#333333",
  defcon: "#FF1D25",
  driving: "#C04605",
  focus: "#CC0000",
  gardening: "#00313B",
  home: "#8D724D",
  ireland: "#004E45",
  law: "#691D26",
  money: "#006A74",
  news: "#13354E",
  newsreview: "#004D6D",
  puzzle: "#C74600",
  register: "#6C6C69",
  saturdayreview: "#A31D24",
  scotland: "#00233E",
  sport: "#008347",
  style: "#BC3385",
  techgames: "#1A1F24",
  thedish: "#DB133B",
  thegame: "#006469",
  thesundaytimesmagazine: "#1D1D1D",
  thetimesmagazine: "#1D1D1D",
  times2: "#622956",
  todaysmagazines: "#1D1D1B",
  travel: "#2C79AD",
  weekend: "#05829A",
  world: "#636C17"
};

const sectionColours = {
  "Arts & Features": sectionColourBase.artsfeatures,
  "Bricks & Mortar": sectionColourBase.bricksmortar,
  Business: sectionColourBase.business,
  Comment: sectionColourBase.comment,
  Culture: sectionColourBase.culture,
  Driving: sectionColourBase.driving,
  Focus: sectionColourBase.focus,
  Gardening: sectionColourBase.gardening,
  Home: sectionColourBase.home,
  Ireland: sectionColourBase.ireland,
  Law: sectionColourBase.law,
  Money: sectionColourBase.money,
  News: sectionColourBase.news,
  "News Review": sectionColourBase.newsreview,
  Puzzle: sectionColourBase.puzzle,
  Register: sectionColourBase.register,
  "Saturday Review": sectionColourBase.saturdayreview,
  Scotland: sectionColourBase.scotland,
  Sport: sectionColourBase.sport,
  Style: sectionColourBase.style,
  "Tech & Games": sectionColourBase.techgames,
  "The Dish": sectionColourBase.thedish,
  "The Game": sectionColourBase.thegame,
  "The Sunday Times Magazine": sectionColourBase.thesundaytimesmagazine,
  "The Times Magazine": sectionColourBase.thetimesmagazine,
  Times2: sectionColourBase.times2,
  "Today's Magazines": sectionColourBase.todaysmagazines,
  Travel: sectionColourBase.travel,
  Weekend: sectionColourBase.weekend,
  World: sectionColourBase.world
};

export default { ...sectionColourBase, ...sectionColours };
