// flow-typed signature: d7117d1b1d0c3b93d09a3aa39a79d4d3
// flow-typed version: <<STUB>>/dextrose_v1.2.14/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dextrose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "dextrose" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "dextrose/bin/run" {
  declare module.exports: any;
}

declare module "dextrose/lib/client/client" {
  declare module.exports: any;
}

declare module "dextrose/lib/client/client.test" {
  declare module.exports: any;
}

declare module "dextrose/lib/client/index" {
  declare module.exports: any;
}

declare module "dextrose/lib/dextrose" {
  declare module.exports: any;
}

declare module "dextrose/lib/index" {
  declare module.exports: any;
}

declare module "dextrose/lib/logger" {
  declare module.exports: any;
}

declare module "dextrose/lib/native-snapper" {
  declare module.exports: any;
}

declare module "dextrose/lib/native-snapper.test" {
  declare module.exports: any;
}

declare module "dextrose/lib/setup-appium" {
  declare module.exports: any;
}

declare module "dextrose/lib/snap-batcher" {
  declare module.exports: any;
}

declare module "dextrose/lib/snap-batcher.test" {
  declare module.exports: any;
}

declare module "dextrose/lib/web-snapper" {
  declare module.exports: any;
}

declare module "dextrose/lib/web-snapper.test" {
  declare module.exports: any;
}

declare module "dextrose/src/client/client" {
  declare module.exports: any;
}

declare module "dextrose/src/client/client.test" {
  declare module.exports: any;
}

declare module "dextrose/src/client/index" {
  declare module.exports: any;
}

declare module "dextrose/src/dextrose" {
  declare module.exports: any;
}

declare module "dextrose/src/index" {
  declare module.exports: any;
}

declare module "dextrose/src/logger" {
  declare module.exports: any;
}

declare module "dextrose/src/native-snapper" {
  declare module.exports: any;
}

declare module "dextrose/src/native-snapper.test" {
  declare module.exports: any;
}

declare module "dextrose/src/setup-appium" {
  declare module.exports: any;
}

declare module "dextrose/src/snap-batcher" {
  declare module.exports: any;
}

declare module "dextrose/src/snap-batcher.test" {
  declare module.exports: any;
}

declare module "dextrose/src/web-snapper" {
  declare module.exports: any;
}

declare module "dextrose/src/web-snapper.test" {
  declare module.exports: any;
}

declare module "dextrose/storiesOfOverloader" {
  declare module.exports: any;
}

// Filename aliases
declare module "dextrose/bin/run.js" {
  declare module.exports: $Exports<"dextrose/bin/run">;
}
declare module "dextrose/index" {
  declare module.exports: $Exports<"dextrose">;
}
declare module "dextrose/index.js" {
  declare module.exports: $Exports<"dextrose">;
}
declare module "dextrose/lib/client/client.js" {
  declare module.exports: $Exports<"dextrose/lib/client/client">;
}
declare module "dextrose/lib/client/client.test.js" {
  declare module.exports: $Exports<"dextrose/lib/client/client.test">;
}
declare module "dextrose/lib/client/index.js" {
  declare module.exports: $Exports<"dextrose/lib/client/index">;
}
declare module "dextrose/lib/dextrose.js" {
  declare module.exports: $Exports<"dextrose/lib/dextrose">;
}
declare module "dextrose/lib/index.js" {
  declare module.exports: $Exports<"dextrose/lib/index">;
}
declare module "dextrose/lib/logger.js" {
  declare module.exports: $Exports<"dextrose/lib/logger">;
}
declare module "dextrose/lib/native-snapper.js" {
  declare module.exports: $Exports<"dextrose/lib/native-snapper">;
}
declare module "dextrose/lib/native-snapper.test.js" {
  declare module.exports: $Exports<"dextrose/lib/native-snapper.test">;
}
declare module "dextrose/lib/setup-appium.js" {
  declare module.exports: $Exports<"dextrose/lib/setup-appium">;
}
declare module "dextrose/lib/snap-batcher.js" {
  declare module.exports: $Exports<"dextrose/lib/snap-batcher">;
}
declare module "dextrose/lib/snap-batcher.test.js" {
  declare module.exports: $Exports<"dextrose/lib/snap-batcher.test">;
}
declare module "dextrose/lib/web-snapper.js" {
  declare module.exports: $Exports<"dextrose/lib/web-snapper">;
}
declare module "dextrose/lib/web-snapper.test.js" {
  declare module.exports: $Exports<"dextrose/lib/web-snapper.test">;
}
declare module "dextrose/src/client/client.js" {
  declare module.exports: $Exports<"dextrose/src/client/client">;
}
declare module "dextrose/src/client/client.test.js" {
  declare module.exports: $Exports<"dextrose/src/client/client.test">;
}
declare module "dextrose/src/client/index.js" {
  declare module.exports: $Exports<"dextrose/src/client/index">;
}
declare module "dextrose/src/dextrose.js" {
  declare module.exports: $Exports<"dextrose/src/dextrose">;
}
declare module "dextrose/src/index.js" {
  declare module.exports: $Exports<"dextrose/src/index">;
}
declare module "dextrose/src/logger.js" {
  declare module.exports: $Exports<"dextrose/src/logger">;
}
declare module "dextrose/src/native-snapper.js" {
  declare module.exports: $Exports<"dextrose/src/native-snapper">;
}
declare module "dextrose/src/native-snapper.test.js" {
  declare module.exports: $Exports<"dextrose/src/native-snapper.test">;
}
declare module "dextrose/src/setup-appium.js" {
  declare module.exports: $Exports<"dextrose/src/setup-appium">;
}
declare module "dextrose/src/snap-batcher.js" {
  declare module.exports: $Exports<"dextrose/src/snap-batcher">;
}
declare module "dextrose/src/snap-batcher.test.js" {
  declare module.exports: $Exports<"dextrose/src/snap-batcher.test">;
}
declare module "dextrose/src/web-snapper.js" {
  declare module.exports: $Exports<"dextrose/src/web-snapper">;
}
declare module "dextrose/src/web-snapper.test.js" {
  declare module.exports: $Exports<"dextrose/src/web-snapper.test">;
}
declare module "dextrose/storiesOfOverloader.js" {
  declare module.exports: $Exports<"dextrose/storiesOfOverloader">;
}
