// flow-typed signature: 7d3d1522ee70343a2a57901a11843d7b
// flow-typed version: <<STUB>>/lodash.get_v4.4.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.get'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "lodash.get" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "lodash.get/index" {
  declare module.exports: $Exports<"lodash.get">;
}
declare module "lodash.get/index.js" {
  declare module.exports: $Exports<"lodash.get">;
}
