const sections = [
  "Arts & Features",
  "Bricks & Mortar",
  "Business",
  "Comment",
  "Culture",
  "Driving",
  "Focus",
  "Gardening",
  "Home",
  "Ireland",
  "Law",
  "Money",
  "News",
  "News Review",
  "Puzzle",
  "Register",
  "Saturday Review",
  "Scotland",
  "Sport",
  "Style",
  "Tech & Games",
  "The Dish",
  "The Game",
  "The Sunday Times Magazine",
  "The Times Magazine",
  "Times2",
  "Today's Magazines",
  "Travel",
  "Weekend",
  "World"
];

export default sections;
