// flow-typed signature: 0cc9a119873ac541bf7d2f8f54209f92
// flow-typed version: <<STUB>>/@times-components/eslint-config-thetimes_v0.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/eslint-config-thetimes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@times-components/eslint-config-thetimes" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "@times-components/eslint-config-thetimes/index" {
  declare module.exports: $Exports<"@times-components/eslint-config-thetimes">;
}
declare module "@times-components/eslint-config-thetimes/index.js" {
  declare module.exports: $Exports<"@times-components/eslint-config-thetimes">;
}
