// flow-typed signature: 274753365c924834020a6bfb02c37a04
// flow-typed version: <<STUB>>/@times-components/storybook_v0.2.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@times-components/storybook" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@times-components/storybook/decorators" {
  declare module.exports: any;
}

// Filename aliases
declare module "@times-components/storybook/decorators.js" {
  declare module.exports: $Exports<"@times-components/storybook/decorators">;
}
