// flow-typed signature: 0823a8791d21c6d3ef67c4f4bb329d91
// flow-typed version: <<STUB>>/@times-components/tealium_v0.1.10/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/tealium'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@times-components/tealium" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@times-components/tealium/__tests__/tealium-send-scheduler.web.test" {
  declare module.exports: any;
}

declare module "@times-components/tealium/coverage/web/lcov-report/prettify" {
  declare module.exports: any;
}

declare module "@times-components/tealium/coverage/web/lcov-report/sorter" {
  declare module.exports: any;
}

declare module "@times-components/tealium/storybook" {
  declare module.exports: any;
}

declare module "@times-components/tealium/tealium-send-scheduler" {
  declare module.exports: any;
}

declare module "@times-components/tealium/tealium" {
  declare module.exports: any;
}

// Filename aliases
declare module "@times-components/tealium/__tests__/tealium-send-scheduler.web.test.js" {
  declare module.exports: $Exports<
    "@times-components/tealium/__tests__/tealium-send-scheduler.web.test"
  >;
}
declare module "@times-components/tealium/coverage/web/lcov-report/prettify.js" {
  declare module.exports: $Exports<
    "@times-components/tealium/coverage/web/lcov-report/prettify"
  >;
}
declare module "@times-components/tealium/coverage/web/lcov-report/sorter.js" {
  declare module.exports: $Exports<
    "@times-components/tealium/coverage/web/lcov-report/sorter"
  >;
}
declare module "@times-components/tealium/storybook.js" {
  declare module.exports: $Exports<"@times-components/tealium/storybook">;
}
declare module "@times-components/tealium/tealium-send-scheduler.js" {
  declare module.exports: $Exports<
    "@times-components/tealium/tealium-send-scheduler"
  >;
}
declare module "@times-components/tealium/tealium.js" {
  declare module.exports: $Exports<"@times-components/tealium/tealium">;
}
