export { default as IconEmail } from "./icons/email";
export { default as IconFacebook } from "./icons/facebook";
export { default as IconForwardArrow } from "./icons/forward-arrow";
export { default as IconStar } from "./icons/star";
export { default as IconTwitter } from "./icons/twitter";
export { default as IconVideo } from "./icons/video";
export { default as IconVideo360Player } from "./icons/video-360-player";
export { default as TheSTLogo } from "./icons/thesundaytimes-logo";
export { default as TheTimesLogo } from "./icons/thetimes-logo";
