// flow-typed signature: fb75f37932931a94e62db3415abd929c
// flow-typed version: <<STUB>>/svgs_v3.1.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svgs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "svgs" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "svgs/example/index" {
  declare module.exports: any;
}

declare module "svgs/index.native" {
  declare module.exports: any;
}

declare module "svgs/lib/index" {
  declare module.exports: any;
}

declare module "svgs/test" {
  declare module.exports: any;
}

// Filename aliases
declare module "svgs/example/index.js" {
  declare module.exports: $Exports<"svgs/example/index">;
}
declare module "svgs/index" {
  declare module.exports: $Exports<"svgs">;
}
declare module "svgs/index.js" {
  declare module.exports: $Exports<"svgs">;
}
declare module "svgs/index.native.js" {
  declare module.exports: $Exports<"svgs/index.native">;
}
declare module "svgs/lib/index.js" {
  declare module.exports: $Exports<"svgs/lib/index">;
}
declare module "svgs/test.js" {
  declare module.exports: $Exports<"svgs/test">;
}
