// @flow
// flow-typed signature: c2913e47eac509a4affac579bd83e6eb
// flow-typed version: <<STUB>>/recursive-readdir-synchronous_v0.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recursive-readdir-synchronous'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "recursive-readdir-synchronous" {
  declare module.exports: (
    filePath: string,
    ignoreGlobs: Array<string | ((file: string, stats: any) => boolean)>
  ) => Array<string>;
}
