// flow-typed signature: 505f2a3191bb925e8f3efd73566188ae
// flow-typed version: <<STUB>>/@times-components/article-summary_v0.7.15/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/article-summary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@times-components/article-summary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@times-components/article-summary/__tests__/article-summary-helper' {
  declare module.exports: any;
}

declare module '@times-components/article-summary/__tests__/article-summary.native.test' {
  declare module.exports: any;
}

declare module '@times-components/article-summary/__tests__/article-summary.web.test' {
  declare module.exports: any;
}

declare module '@times-components/article-summary/article-summary-renderer' {
  declare module.exports: any;
}

declare module '@times-components/article-summary/article-summary' {
  declare module.exports: any;
}

declare module '@times-components/article-summary/article-summary.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module '@times-components/article-summary/__tests__/article-summary-helper.js' {
  declare module.exports: $Exports<'@times-components/article-summary/__tests__/article-summary-helper'>;
}
declare module '@times-components/article-summary/__tests__/article-summary.native.test.js' {
  declare module.exports: $Exports<'@times-components/article-summary/__tests__/article-summary.native.test'>;
}
declare module '@times-components/article-summary/__tests__/article-summary.web.test.js' {
  declare module.exports: $Exports<'@times-components/article-summary/__tests__/article-summary.web.test'>;
}
declare module '@times-components/article-summary/article-summary-renderer.js' {
  declare module.exports: $Exports<'@times-components/article-summary/article-summary-renderer'>;
}
declare module '@times-components/article-summary/article-summary.js' {
  declare module.exports: $Exports<'@times-components/article-summary/article-summary'>;
}
declare module '@times-components/article-summary/article-summary.stories.js' {
  declare module.exports: $Exports<'@times-components/article-summary/article-summary.stories'>;
}
