// flow-typed signature: 57190c741cfca8dff39d373954d8080b
// flow-typed version: <<STUB>>/@times-components/card_v0.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/card'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@times-components/card' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@times-components/card/__tests__/android/card.android.test' {
  declare module.exports: any;
}

declare module '@times-components/card/__tests__/android/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/card/__tests__/card.native.test' {
  declare module.exports: any;
}

declare module '@times-components/card/__tests__/ios/card.ios.test' {
  declare module.exports: any;
}

declare module '@times-components/card/__tests__/ios/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/card/__tests__/web/card.web.test' {
  declare module.exports: any;
}

declare module '@times-components/card/__tests__/web/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/card/card-loading' {
  declare module.exports: any;
}

declare module '@times-components/card/card-loading.web' {
  declare module.exports: any;
}

declare module '@times-components/card/card-styles.web' {
  declare module.exports: any;
}

declare module '@times-components/card/card' {
  declare module.exports: any;
}

declare module '@times-components/card/card.stories' {
  declare module.exports: any;
}

declare module '@times-components/card/card.stories.web' {
  declare module.exports: any;
}

declare module '@times-components/card/card.web' {
  declare module.exports: any;
}

// Filename aliases
declare module '@times-components/card/__tests__/android/card.android.test.js' {
  declare module.exports: $Exports<'@times-components/card/__tests__/android/card.android.test'>;
}
declare module '@times-components/card/__tests__/android/jest.config.js' {
  declare module.exports: $Exports<'@times-components/card/__tests__/android/jest.config'>;
}
declare module '@times-components/card/__tests__/card.native.test.js' {
  declare module.exports: $Exports<'@times-components/card/__tests__/card.native.test'>;
}
declare module '@times-components/card/__tests__/ios/card.ios.test.js' {
  declare module.exports: $Exports<'@times-components/card/__tests__/ios/card.ios.test'>;
}
declare module '@times-components/card/__tests__/ios/jest.config.js' {
  declare module.exports: $Exports<'@times-components/card/__tests__/ios/jest.config'>;
}
declare module '@times-components/card/__tests__/web/card.web.test.js' {
  declare module.exports: $Exports<'@times-components/card/__tests__/web/card.web.test'>;
}
declare module '@times-components/card/__tests__/web/jest.config.js' {
  declare module.exports: $Exports<'@times-components/card/__tests__/web/jest.config'>;
}
declare module '@times-components/card/card-loading.js' {
  declare module.exports: $Exports<'@times-components/card/card-loading'>;
}
declare module '@times-components/card/card-loading.web.js' {
  declare module.exports: $Exports<'@times-components/card/card-loading.web'>;
}
declare module '@times-components/card/card-styles.web.js' {
  declare module.exports: $Exports<'@times-components/card/card-styles.web'>;
}
declare module '@times-components/card/card.js' {
  declare module.exports: $Exports<'@times-components/card/card'>;
}
declare module '@times-components/card/card.stories.js' {
  declare module.exports: $Exports<'@times-components/card/card.stories'>;
}
declare module '@times-components/card/card.stories.web.js' {
  declare module.exports: $Exports<'@times-components/card/card.stories.web'>;
}
declare module '@times-components/card/card.web.js' {
  declare module.exports: $Exports<'@times-components/card/card.web'>;
}
