// flow-typed signature: b2ea11c0154199eb38bfd5da6fb42a9a
// flow-typed version: <<STUB>>/@times-components/icons_v0.1.5/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@times-components/icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@times-components/icons/__tests__/android/icons.test' {
  declare module.exports: any;
}

declare module '@times-components/icons/__tests__/android/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/icons/__tests__/ios/icons.test' {
  declare module.exports: any;
}

declare module '@times-components/icons/__tests__/ios/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/icons/__tests__/shared' {
  declare module.exports: any;
}

declare module '@times-components/icons/__tests__/web/icons.test' {
  declare module.exports: any;
}

declare module '@times-components/icons/__tests__/web/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/icons/icons' {
  declare module.exports: any;
}

declare module '@times-components/icons/icons.stories' {
  declare module.exports: any;
}

declare module '@times-components/icons/icons/chevron/left' {
  declare module.exports: any;
}

declare module '@times-components/icons/icons/chevron/right' {
  declare module.exports: any;
}

declare module '@times-components/icons/icons/diamond' {
  declare module.exports: any;
}

declare module '@times-components/icons/icons/twitter' {
  declare module.exports: any;
}

declare module '@times-components/icons/styles/index.android' {
  declare module.exports: any;
}

declare module '@times-components/icons/styles/index.ios' {
  declare module.exports: any;
}

declare module '@times-components/icons/styles/index' {
  declare module.exports: any;
}

declare module '@times-components/icons/styles/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module '@times-components/icons/__tests__/android/icons.test.js' {
  declare module.exports: $Exports<'@times-components/icons/__tests__/android/icons.test'>;
}
declare module '@times-components/icons/__tests__/android/jest.config.js' {
  declare module.exports: $Exports<'@times-components/icons/__tests__/android/jest.config'>;
}
declare module '@times-components/icons/__tests__/ios/icons.test.js' {
  declare module.exports: $Exports<'@times-components/icons/__tests__/ios/icons.test'>;
}
declare module '@times-components/icons/__tests__/ios/jest.config.js' {
  declare module.exports: $Exports<'@times-components/icons/__tests__/ios/jest.config'>;
}
declare module '@times-components/icons/__tests__/shared.js' {
  declare module.exports: $Exports<'@times-components/icons/__tests__/shared'>;
}
declare module '@times-components/icons/__tests__/web/icons.test.js' {
  declare module.exports: $Exports<'@times-components/icons/__tests__/web/icons.test'>;
}
declare module '@times-components/icons/__tests__/web/jest.config.js' {
  declare module.exports: $Exports<'@times-components/icons/__tests__/web/jest.config'>;
}
declare module '@times-components/icons/icons.js' {
  declare module.exports: $Exports<'@times-components/icons/icons'>;
}
declare module '@times-components/icons/icons.stories.js' {
  declare module.exports: $Exports<'@times-components/icons/icons.stories'>;
}
declare module '@times-components/icons/icons/chevron/left.js' {
  declare module.exports: $Exports<'@times-components/icons/icons/chevron/left'>;
}
declare module '@times-components/icons/icons/chevron/right.js' {
  declare module.exports: $Exports<'@times-components/icons/icons/chevron/right'>;
}
declare module '@times-components/icons/icons/diamond.js' {
  declare module.exports: $Exports<'@times-components/icons/icons/diamond'>;
}
declare module '@times-components/icons/icons/twitter.js' {
  declare module.exports: $Exports<'@times-components/icons/icons/twitter'>;
}
declare module '@times-components/icons/styles/index.android.js' {
  declare module.exports: $Exports<'@times-components/icons/styles/index.android'>;
}
declare module '@times-components/icons/styles/index.ios.js' {
  declare module.exports: $Exports<'@times-components/icons/styles/index.ios'>;
}
declare module '@times-components/icons/styles/index.js' {
  declare module.exports: $Exports<'@times-components/icons/styles/index'>;
}
declare module '@times-components/icons/styles/shared.js' {
  declare module.exports: $Exports<'@times-components/icons/styles/shared'>;
}
