// flow-typed signature: 8bef99682bc305a042702f349b66d746
// flow-typed version: <<STUB>>/@times-components/jest-configurator_v0.0.17/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/jest-configurator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@times-components/jest-configurator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@times-components/jest-configurator/__tests__/coverage.test' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/__tests__/jest-configurator.test' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/all/component.android' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/all/component.ios' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/all/component.web' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/android/component.android' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/android/component' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ignore/__tests__/component.test' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ignore/component.fructose.web' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ignore/data-helper' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ignore/fixtures/fixture-generator' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ignore/ignore' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ignore/ignore.stories' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ignore/ignore.stories.native' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ignore/ignore.stories.web' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ios/component.ios' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/ios/component' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/nested/component' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/nested/component.web' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/nested/styles/android/index.android' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/nested/styles/shared' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/simple/simple' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/unknown/unknown.platform' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/web-native/component' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/fixtures/web-native/component.web' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/flow-typed/npm/find-node-modules_vx.x.x' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/flow-typed/npm/recursive-readdir-synchronous_vx.x.x' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/lib/coverage' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/lib/jest-configurator' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/setup-jest' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/src/coverage' {
  declare module.exports: any;
}

declare module '@times-components/jest-configurator/src/jest-configurator' {
  declare module.exports: any;
}

// Filename aliases
declare module '@times-components/jest-configurator/__tests__/coverage.test.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/__tests__/coverage.test'>;
}
declare module '@times-components/jest-configurator/__tests__/jest-configurator.test.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/__tests__/jest-configurator.test'>;
}
declare module '@times-components/jest-configurator/fixtures/all/component.android.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/all/component.android'>;
}
declare module '@times-components/jest-configurator/fixtures/all/component.ios.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/all/component.ios'>;
}
declare module '@times-components/jest-configurator/fixtures/all/component.web.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/all/component.web'>;
}
declare module '@times-components/jest-configurator/fixtures/android/component.android.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/android/component.android'>;
}
declare module '@times-components/jest-configurator/fixtures/android/component.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/android/component'>;
}
declare module '@times-components/jest-configurator/fixtures/ignore/__tests__/component.test.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ignore/__tests__/component.test'>;
}
declare module '@times-components/jest-configurator/fixtures/ignore/component.fructose.web.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ignore/component.fructose.web'>;
}
declare module '@times-components/jest-configurator/fixtures/ignore/data-helper.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ignore/data-helper'>;
}
declare module '@times-components/jest-configurator/fixtures/ignore/fixtures/fixture-generator.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ignore/fixtures/fixture-generator'>;
}
declare module '@times-components/jest-configurator/fixtures/ignore/ignore.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ignore/ignore'>;
}
declare module '@times-components/jest-configurator/fixtures/ignore/ignore.stories.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ignore/ignore.stories'>;
}
declare module '@times-components/jest-configurator/fixtures/ignore/ignore.stories.native.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ignore/ignore.stories.native'>;
}
declare module '@times-components/jest-configurator/fixtures/ignore/ignore.stories.web.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ignore/ignore.stories.web'>;
}
declare module '@times-components/jest-configurator/fixtures/ios/component.ios.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ios/component.ios'>;
}
declare module '@times-components/jest-configurator/fixtures/ios/component.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/ios/component'>;
}
declare module '@times-components/jest-configurator/fixtures/nested/component.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/nested/component'>;
}
declare module '@times-components/jest-configurator/fixtures/nested/component.web.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/nested/component.web'>;
}
declare module '@times-components/jest-configurator/fixtures/nested/styles/android/index.android.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/nested/styles/android/index.android'>;
}
declare module '@times-components/jest-configurator/fixtures/nested/styles/shared.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/nested/styles/shared'>;
}
declare module '@times-components/jest-configurator/fixtures/simple/simple.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/simple/simple'>;
}
declare module '@times-components/jest-configurator/fixtures/unknown/unknown.platform.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/unknown/unknown.platform'>;
}
declare module '@times-components/jest-configurator/fixtures/web-native/component.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/web-native/component'>;
}
declare module '@times-components/jest-configurator/fixtures/web-native/component.web.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/fixtures/web-native/component.web'>;
}
declare module '@times-components/jest-configurator/flow-typed/npm/find-node-modules_vx.x.x.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/flow-typed/npm/find-node-modules_vx.x.x'>;
}
declare module '@times-components/jest-configurator/flow-typed/npm/recursive-readdir-synchronous_vx.x.x.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/flow-typed/npm/recursive-readdir-synchronous_vx.x.x'>;
}
declare module '@times-components/jest-configurator/lib/coverage.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/lib/coverage'>;
}
declare module '@times-components/jest-configurator/lib/jest-configurator.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/lib/jest-configurator'>;
}
declare module '@times-components/jest-configurator/setup-jest.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/setup-jest'>;
}
declare module '@times-components/jest-configurator/src/coverage.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/src/coverage'>;
}
declare module '@times-components/jest-configurator/src/jest-configurator.js' {
  declare module.exports: $Exports<'@times-components/jest-configurator/src/jest-configurator'>;
}
