// flow-typed signature: b38af430f98e0f721808adf565fc4368
// flow-typed version: <<STUB>>/@times-components/link_v0.1.13/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@times-components/link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@times-components/link/__tests__/android/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/link/__tests__/android/link.android.test' {
  declare module.exports: any;
}

declare module '@times-components/link/__tests__/ios/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/link/__tests__/ios/link.ios.test' {
  declare module.exports: any;
}

declare module '@times-components/link/__tests__/shared' {
  declare module.exports: any;
}

declare module '@times-components/link/__tests__/web/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/link/__tests__/web/link.web.test' {
  declare module.exports: any;
}

declare module '@times-components/link/link.android' {
  declare module.exports: any;
}

declare module '@times-components/link/link' {
  declare module.exports: any;
}

declare module '@times-components/link/link.stories' {
  declare module.exports: any;
}

declare module '@times-components/link/link.web' {
  declare module.exports: any;
}

declare module '@times-components/link/text-link' {
  declare module.exports: any;
}

// Filename aliases
declare module '@times-components/link/__tests__/android/jest.config.js' {
  declare module.exports: $Exports<'@times-components/link/__tests__/android/jest.config'>;
}
declare module '@times-components/link/__tests__/android/link.android.test.js' {
  declare module.exports: $Exports<'@times-components/link/__tests__/android/link.android.test'>;
}
declare module '@times-components/link/__tests__/ios/jest.config.js' {
  declare module.exports: $Exports<'@times-components/link/__tests__/ios/jest.config'>;
}
declare module '@times-components/link/__tests__/ios/link.ios.test.js' {
  declare module.exports: $Exports<'@times-components/link/__tests__/ios/link.ios.test'>;
}
declare module '@times-components/link/__tests__/shared.js' {
  declare module.exports: $Exports<'@times-components/link/__tests__/shared'>;
}
declare module '@times-components/link/__tests__/web/jest.config.js' {
  declare module.exports: $Exports<'@times-components/link/__tests__/web/jest.config'>;
}
declare module '@times-components/link/__tests__/web/link.web.test.js' {
  declare module.exports: $Exports<'@times-components/link/__tests__/web/link.web.test'>;
}
declare module '@times-components/link/link.android.js' {
  declare module.exports: $Exports<'@times-components/link/link.android'>;
}
declare module '@times-components/link/link.js' {
  declare module.exports: $Exports<'@times-components/link/link'>;
}
declare module '@times-components/link/link.stories.js' {
  declare module.exports: $Exports<'@times-components/link/link.stories'>;
}
declare module '@times-components/link/link.web.js' {
  declare module.exports: $Exports<'@times-components/link/link.web'>;
}
declare module '@times-components/link/text-link.js' {
  declare module.exports: $Exports<'@times-components/link/text-link'>;
}
