// flow-typed signature: 376a1c25c870c0e01edbbfe4496c52b6
// flow-typed version: <<STUB>>/@times-components/responsive-styles_v0.2.13/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@times-components/responsive-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@times-components/responsive-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@times-components/responsive-styles/__tests__/web/jest.config' {
  declare module.exports: any;
}

declare module '@times-components/responsive-styles/__tests__/web/responsive-styles.test' {
  declare module.exports: any;
}

declare module '@times-components/responsive-styles/responsive-styles' {
  declare module.exports: any;
}

declare module '@times-components/responsive-styles/responsive-styles.stories.web' {
  declare module.exports: any;
}

// Filename aliases
declare module '@times-components/responsive-styles/__tests__/web/jest.config.js' {
  declare module.exports: $Exports<'@times-components/responsive-styles/__tests__/web/jest.config'>;
}
declare module '@times-components/responsive-styles/__tests__/web/responsive-styles.test.js' {
  declare module.exports: $Exports<'@times-components/responsive-styles/__tests__/web/responsive-styles.test'>;
}
declare module '@times-components/responsive-styles/responsive-styles.js' {
  declare module.exports: $Exports<'@times-components/responsive-styles/responsive-styles'>;
}
declare module '@times-components/responsive-styles/responsive-styles.stories.web.js' {
  declare module.exports: $Exports<'@times-components/responsive-styles/responsive-styles.stories.web'>;
}
